---
- hosts: 3.95.213.193
  vars:
    server_ip: 3.95.213.193
    server_dns: ec2-3-95-213-193.compute-1.amazonaws.com

  tasks:
    - name: Creates tmp directory
      file:
        path: ./tmp
        state: directory

    - name: Copy index.html file
      template: src=../index.html.j2 dest=/home/ec2-user/tmp/index.html
  
  
- hosts: 35.174.109.195
  vars:
    server_ip: 35.174.109.195
    server_dns: ec2-35-174-109-195.compute-1.amazonaws.com

  tasks:
    - name: Creates tmp directory
      file:
        path: ./tmp
        state: directory

    - name: Copy index.html file
      template: src=../index.html.j2 dest=/home/ec2-user/tmp/index.html